[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/jahandarm"
    weight = 3
    
# Social Media Configuration

# [[social]]
#    identifier = "instagram"
#    name = "Instagram"
#    url = "#"
#    weight = 2